{% set version = "1.93.4" %}

package:
  name: circularmapper
  version: {{ version }}

source:
  fn: generator-{{ version }}.jar
  url: https://github.com/apeltzer/circularmapper/releases/download/v{{ version }}/generator-{{ version }}.jar
  sha256: b91e0a58761f9854a89c526c45e58f716ccb5bcb456d2e9707fc127865c74f79 

build:
  number: 0

requirements:
  build:
    - wget
  run:
    - openjdk
    - python

test:
  commands:
    - circulargenerator > /dev/null
    - realignsamfile > /dev/null

about:
  home: https://github.com/apeltzer/CircularMapper
  license: GPLv3
  summary: " A method to improve mappings on circular genomes, using the BWA mapper."
